# BASE de dados generica y tabelas para casi todos os juegos simples que pude imaginar

DROP DATABASE IF EXISTS GameSO;
CREATE DATABASE GameSO;
USE GameSO;

CREATE TABLE Player(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Username VARCHAR(25) NOT NULL,
	Password VARCHAR(25) NOT NULL,
	Ativo BIT DEFAULT 1
)AUTO_INCREMENT = 1;

CREATE TABLE Game(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Inicio TIMESTAMP NOT NULL DEFAULT NOW(),
	Duracion INT,
	Vencedor INT,
	Ativo BIT DEFAULT 1,
	FOREIGN KEY (Vencedor) REFERENCES Player(ID)
)AUTO_INCREMENT = 1;

CREATE TABLE Relaciona(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDg INT NOT NULL,
	IDp INT NOT NULL,
	Score INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (IDp) REFERENCES Player(ID),
	FOREIGN KEY (IDg) REFERENCES Game(ID)
)AUTO_INCREMENT = 1;

INSERT INTO Player (Username, Password) VALUES ('Jose', '1qaz2wsx');
INSERT INTO Player (Username, Password) VALUES ('Luiz', '2wsx3edc');

INSERT INTO Game (Duracion,Vencedor) VALUES (33,1);
INSERT INTO Game (Duracion,Vencedor) VALUES (30,2);

INSERT INTO Relaciona (IDg,IDp) VALUES (1,1);
INSERT INTO Relaciona (IDg,IDp) VALUES (1,2);

